export const items = [
  {
    id: 0,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "kadin",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Yeni"],
    discount: 5,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 1,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "unisex",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Çok satan"],
    discount: 0,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 2,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "unisex",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: [],
    discount: 0,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 3,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "erkek",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Yeni", "Çok satan"],
    discount: 0,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 4,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "kadin",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Çok satan"],
    discount: 0,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 5,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "erkek",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Çok satan"],
    discount: 20,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 6,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "erkek",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Yeni", "Çok satan"],
    discount: 50,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 7,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "unisex",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Yeni"],
    discount: 10,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 8,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "erkek",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Yeni"],
    discount: 0,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
  {
    id: 9,
    title: "Lorem ipsum dolor.",
    price: 500,
    img: "https://images.pexels.com/photos/1557980/pexels-photo-1557980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    sex: "kadin",
    gr: 15,
    slug: "lorem-ipsum-slug",
    ribbon: ["Yeni", "Çok satan"],
    discount: 0,
    stock: true,
    desc: "Lorem ipsum ürünü zort. Yok böyle bir koku uleee. Alın şunu.",
    tags: ["koku", "parfum", "esans"],
    comments: [
      {
        userId: 0,
        text: "Harika bir urun ulee",
        star: 5,
      },
    ],
  },
];
